spring.application.name=tripAssistantBE

spring.datasource.url=${DATABASE_URL:overwriteMe}
spring.datasource.username=${DATABASE_USERNAME:overwriteMe}
spring.datasource.password=${DATABASE_PASSWORD:overwriteMe}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=admin